Section "ServerLayout"
    Identifier     "Default Layout"
    Option         "BlankTime" "0"
    Option         "StandbyTime" "0"
    Option         "SuspendTime" "0"
    Option         "OffTime" "0"
EndSection

Section "Extensions"
    Option "DPMS" "Disable"
EndSection
